"""Render the digest into a styled HTML email and send it via Gmail SMTP."""

from __future__ import annotations

import datetime
import os
import smtplib
from email.message import EmailMessage

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587

# Inline styles so the email renders consistently across mail clients.
EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0; padding:0; background:#f4f5f7;">
  <div style="max-width:640px; margin:0 auto; padding:24px 20px;
       font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;
       color:#1a1a2e; background:#f4f5f7;">
    <div style="background:#ffffff; border-radius:14px; padding:28px 26px;
         box-shadow:0 1px 3px rgba(0,0,0,0.08);">
      <div style="border-bottom:2px solid #eef0f3; padding-bottom:14px; margin-bottom:8px;">
        <div style="font-size:22px; font-weight:700;">📰 Your Morning Brief</div>
        <div style="font-size:13px; color:#8a8f98; margin-top:4px;">{date} · AI · Research · Markets · Geopolitics</div>
      </div>
      {content}
      <div style="border-top:1px solid #eef0f3; margin-top:22px; padding-top:14px;
           font-size:12px; color:#a0a4ab;">
        Generated by myNews with Gemini + live web search. Stay curious. ☕
      </div>
    </div>
  </div>
</body>
</html>
"""

# Scoped styling applied to the Gemini-produced fragment via a wrapper class.
FRAGMENT_STYLE = """
<style>
  .digest h2 { font-size:16px; margin:22px 0 8px; color:#12123a; }
  .digest ul { margin:0 0 6px; padding-left:20px; }
  .digest li { margin:6px 0; font-size:14px; line-height:1.5; color:#2a2a3a; }
  .digest p { font-size:14px; line-height:1.6; color:#2a2a3a; margin:6px 0; }
  .digest strong { color:#12123a; }
  .digest table { width:100%; border-collapse:collapse; margin:8px 0 6px; font-size:13px; }
  .digest th { text-align:left; background:#f0f2f5; padding:8px 10px; color:#4a4f58;
       border-bottom:2px solid #e2e5ea; }
  .digest td { padding:8px 10px; border-bottom:1px solid #eef0f3; color:#2a2a3a; }
  .digest tr:last-child td { border-bottom:none; }
</style>
"""


def build_email_html(fragment: str) -> str:
    date = datetime.datetime.now(
        datetime.timezone(datetime.timedelta(hours=-8))
    ).strftime("%A, %B %d, %Y")
    content = FRAGMENT_STYLE + f'<div class="digest">{fragment}</div>'
    return EMAIL_TEMPLATE.format(date=date, content=content)


def send_email(html: str) -> None:
    sender = os.environ["GMAIL_ADDRESS"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    recipient = os.environ["RECIPIENT"]

    date = datetime.datetime.now(
        datetime.timezone(datetime.timedelta(hours=-8))
    ).strftime("%b %d")

    msg = EmailMessage()
    msg["Subject"] = f"📰 Your Morning Brief — {date}"
    msg["From"] = sender
    msg["To"] = recipient
    msg.set_content(
        "Your morning brief is best viewed in an HTML-capable email client."
    )
    msg.add_alternative(html, subtype="html")

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)
